# Generated by Django 3.0.3 on 2020-04-18 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default=None, max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('organizer', models.CharField(max_length=20)),
                ('event_date', models.DateField()),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=200)),
                ('poster', models.ImageField(default='default.jpg', upload_to='poster')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('requested_time', models.TimeField()),
                ('purpose', models.CharField(max_length=100)),
                ('is_principal_accepted', models.IntegerField(default=0)),
                ('principal_comments', models.TextField(default='None')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
